### ISSUE TITLE
Undefined values

### ISSUE THREAD

**Issue by devmeireles** [RemiV2/11-builder#1]
Algunas informaciones dentro del `let getData = url =>` no estaban volvendo los valores correctos, creo qué el Fifaindex puede ter cambiado la estructura HTML. Conseguí volver usando:

`player.id = $(row).data('playerid')`
`player.name = $(row).data('title', 'Name').find('a').attr('title')`
`player.rating = {`
	`initial: $(row).data('title', 'OVR / POT').find('span').first().text(),`
	`potential: $(row).data('title', 'OVR / POT').find('span').eq(1).text()`
`}`

`player.photo = urlRoot + $(row).find('img.player.small').attr('src')`
`player.club = {`
	`name: $(row).find("td[data-title='Team'] a").attr('title'),`
	`logo: urlRoot + $(row).find('img.team.small').attr('src')`
`}`
`const positions = []`
`for (const position of Array.from($(row).data('title', 'Preferred Positions').find('a.link-position'))) {`
	`positions.push($(position).text())`
`}`

**Comment by remidej** [comment]
Thanks for the heads-up, I haven't run that script in a while.

Do the changes you're suggesting fix the issue ? If so, could you please submit a pull request ?
